### ISSUE TITLE
NotificationFeed doesn't update when NewActivitiesNotification clicked

### ISSUE THREAD

**Issue by mikestaub** [GetStream/react-activity-feed#5]
I am using the simplest example:

```
<StreamApp
  apiKey="3fjzn67nznwt"
  appId="41814"
  token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZXhhbXBsZS11c2VyIn0.XEKjtzD2AIQMLXH6kfJlL8P_JV4CBYvcMsmQCFjyY2U"
>
  <NotificationFeed notify={true} />
</StreamApp>
```

I expect the Feed to render with the new activities when I click the notification.

For a workaround, I am storing a timestamp in the component state, then setting the Feed's 'key' prop to a new timestamp when the user clicks the Notifier to force a rerender.

**Comment by jaapbakker88** [comment]
Thanks for reporting this. We just published a new version of the library that addresses this issue. Could you try it out and confirm it's working now?

**Comment by mikestaub** [comment]
I tried it out but it is still not working. Can you link to the PR or commit with the fix?

**Comment by JelteF** [comment]
This one should fix it: https://github.com/GetStream/react-activity-feed/commit/bb1855f02d7a0f9365bf897652da4b29f6b49f4e

Are you using 0.5.6?

**Comment by mikestaub** [comment]
Yes, I am on the latest, can you link to an example with proper usage?

**Comment by JelteF** [comment]
Hmm, that's weird. Just to be clear on the issue then:
- You do see the light blue Notifier pop up with a number of missing activities, but when you click it nothing happens?

**Comment by JelteF** [comment]
Other question, the NewActivitiesNotifaciotn stays there and it doesn't disapear after clicking it?

**Comment by mikestaub** [comment]
That's correct.
